### ISSUE TITLE
url doesn't allow trailing slashes

### ISSUE THREAD

**Issue by WhoSoup** [AdamSLevy/jsonrpc2#1]
using "https://api.factomd.net/" as the url results in a 403 forbidden, but "https://api.factomd.net" works

**Comment by AdamSLevy** [comment]
I do not believe this is an issue with this library. This is likely an issue with the server that is hosting that endpoint. 

In this specific case, you probably want "https://api.factomd.net/v2"

**Comment by WhoSoup** [comment]
you're right, my bad. it's an issue with the factom library that calls this. will open a new issue
